FLASK_DEBUG=True
FLASK_CONFIG=application.config.DevelopmentConfig
FLASK_APP=application.wsgi:app
SECRET_KEY=replaceinprod
DATABASE_URL=postgresql://localhost/development_plan_timetable
DATABASE_URL_UPGRADE=postgresql://localhost/development_plan_timetable
FLASK_RUN_PORT=5050
