# syntax=docker/dockerfile:1
FROM python:3.13-slim-trixie
WORKDIR /code

ENV FLASK_APP=application.wsgi:app
ENV FLASK_CONFIG=application.config.DevelopmentConfig

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN pip install -r requirements/requirements.txt
CMD [ "flask", "db", "upgrade" ]
