"""candidate document table

Revision ID: 079dc058c2fa
Revises: b13af51a3d19
Create Date: 2024-10-10 17:48:12.171421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '079dc058c2fa'
down_revision = 'b13af51a3d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACCEPT', 'REJECT', name='documentstatus').create(op.get_bind())
    op.create_table('candidate_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('local_plan', sa.Text(), nullable=False),
    sa.Column('documentation_url', sa.Text(), nullable=True),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACCEPT', 'REJECT', name='documentstatus', create_type=False), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['local_plan'], ['local_plan.reference'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_document')
    sa.Enum('ACCEPT', 'REJECT', name='documentstatus').drop(op.get_bind())
    # ### end Alembic commands ###
