"""add enum for timetable published

Revision ID: 07b7215fc0c9
Revises: 88a63e5395a6
Create Date: 2024-11-11 17:35:53.076094

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '07b7215fc0c9'
down_revision = '88a63e5395a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'eventcategory', ['TIMETABLE_PUBLISHED', 'ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'PLANNING_INSPECTORATE_EXAMINATION', 'PLANNING_INSPECTORATE_FINDINGS'],
                        [TableReference(table_schema='public', table_name='local_plan_event', column_name='event_category'), TableReference(table_schema='public', table_name='local_plan_event_type', column_name='event_category')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'eventcategory', ['ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'PLANNING_INSPECTORATE_EXAMINATION', 'PLANNING_INSPECTORATE_FINDINGS'],
                        [TableReference(table_schema='public', table_name='local_plan_event', column_name='event_category'), TableReference(table_schema='public', table_name='local_plan_event_type', column_name='event_category')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
