"""add category to local plan event

Revision ID: 0ccad9b38d39
Revises: ff224e3917b3
Create Date: 2024-10-29 11:04:08.685463

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ccad9b38d39"
down_revision = "ff224e3917b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("local_plan_event", schema=None) as batch_op:
        batch_op.drop_column("event_date")

    with op.batch_alter_table("local_plan_event_type", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_category", sa.Text(), nullable=True))

    op.execute(
        """UPDATE local_plan_event_type
               SET event_category = CASE
                WHEN reference LIKE 'estimated-reg-18%' THEN 'estimated-regulation-18'
                WHEN reference LIKE 'estimated-reg-19%' THEN 'estimated-regulation-19'
                WHEN reference LIKE '%reg-18%' THEN 'regulation-18'
                WHEN reference LIKE '%reg-19%' THEN 'regulation-19'
                WHEN reference LIKE 'estimated-%' THEN 'estimated-examination-and-adoption'
                ELSE 'examination-and-adoption'
                END;"""
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("local_plan_event_type", schema=None) as batch_op:
        batch_op.drop_column("event_category")

    with op.batch_alter_table("local_plan_event", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("event_date", sa.TEXT(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
