"""drop redundant boolean field on document

Revision ID: 2657afc2a05b
Revises: 98084b915d36
Create Date: 2024-09-27 10:18:30.350477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2657afc2a05b'
down_revision = '98084b915d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_document', schema=None) as batch_op:
        batch_op.drop_column('inlcude_in_dataset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inlcude_in_dataset', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
