"""rework event and timetable types

Revision ID: 292c6036861b
Revises: ff224e3917b3
Create Date: 2024-10-29 14:58:30.227660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '292c6036861b'
down_revision = 'ff224e3917b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'EXAMINATION_AND_ADOPTION', name='eventcategory').create(op.get_bind())
    with op.batch_alter_table('local_plan_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_category', postgresql.ENUM('ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'EXAMINATION_AND_ADOPTION', name='eventcategory', create_type=False), nullable=False))
        batch_op.add_column(sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_constraint('local_plan_event_event_type_fkey', type_='foreignkey')
        batch_op.drop_column('event_month')
        batch_op.drop_column('event_year')
        batch_op.drop_column('event_type')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_day', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_year', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_month', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('local_plan_event_event_type_fkey', 'local_plan_event_type', ['event_type'], ['reference'])
        batch_op.drop_column('event_data')
        batch_op.drop_column('event_category')

    sa.Enum('ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'EXAMINATION_AND_ADOPTION', name='eventcategory').drop(op.get_bind())
    # ### end Alembic commands ###
