"""local plan event column rename

Revision ID: 3a72fbbad936
Revises: 80831df842ca
Create Date: 2024-12-06 12:58:47.999548

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3a72fbbad936"
down_revision = "80831df842ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("local_plan_event", schema=None) as batch_op:
        batch_op.alter_column(
            "local_plan_event_type_reference",
            new_column_name="local_plan_event",
            existing_type=sa.Text(),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("local_plan_event", schema=None) as batch_op:
        batch_op.alter_column(
            "local_plan_event",
            new_column_name="local_plan_event_type_reference",
            existing_type=sa.Text(),
        )

    # ### end Alembic commands ###
