"""drop plan boundary type

Revision ID: 3fb32534880e
Revises: df8fe8c2526a
Create Date: 2024-11-20 08:44:09.955673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb32534880e'
down_revision = 'df8fe8c2526a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_boundary', schema=None) as batch_op:
        batch_op.drop_column('plan_boundary_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_boundary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_boundary_type', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
