"""add website to org

Revision ID: 4913d55febd6
Revises: 59d28e7fd16f
Create Date: 2024-10-09 09:54:36.519916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4913d55febd6'
down_revision = '59d28e7fd16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan', schema=None) as batch_op:
        batch_op.alter_column('boundary_status',
               existing_type=postgresql.ENUM('FOR_REVIEW', 'FOR_PUBLICATION', 'NOT_FOR_PUBLICATION', 'PUBLISHED', name='status'),
               nullable=False)

    with op.batch_alter_table('local_plan_document', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('FOR_REVIEW', 'FOR_PUBLICATION', 'NOT_FOR_PUBLICATION', 'PUBLISHED', name='status'),
               nullable=True)

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_column('website')

    with op.batch_alter_table('local_plan_document', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('FOR_REVIEW', 'FOR_PUBLICATION', 'NOT_FOR_PUBLICATION', 'PUBLISHED', name='status'),
               nullable=False)

    with op.batch_alter_table('local_plan', schema=None) as batch_op:
        batch_op.alter_column('boundary_status',
               existing_type=postgresql.ENUM('FOR_REVIEW', 'FOR_PUBLICATION', 'NOT_FOR_PUBLICATION', 'PUBLISHED', name='status'),
               nullable=True)

    # ### end Alembic commands ###
