"""drop candidate documents

Revision ID: 5e2f287db4b7
Revises: 9909dd8cf934
Create Date: 2024-11-29 11:43:38.826630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e2f287db4b7'
down_revision = '9909dd8cf934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_document')
    sa.Enum('ACCEPT', 'REJECT', name='documentstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACCEPT', 'REJECT', name='documentstatus').create(op.get_bind())
    op.create_table('candidate_document',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('local_plan', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('documentation_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACCEPT', 'REJECT', name='documentstatus', create_type=False), autoincrement=False, nullable=True),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['local_plan'], ['local_plan.reference'], name='candidate_document_local_plan_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidate_document_pkey')
    )
    # ### end Alembic commands ###
