"""additional indexes

Revision ID: 5e9dad0d78ed
Revises: 8896589fffa8
Create Date: 2024-10-24 17:01:30.225924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9dad0d78ed'
down_revision = '8896589fffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_plan_end_date'), ['end_date'], unique=False)

    with op.batch_alter_table('local_plan_boundary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_plan_boundary_end_date'), ['end_date'], unique=False)

    with op.batch_alter_table('local_plan_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_plan_document_end_date'), ['end_date'], unique=False)

    with op.batch_alter_table('local_plan_organisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_plan_organisation_local_plan'), ['local_plan'], unique=False)
        batch_op.create_index(batch_op.f('ix_local_plan_organisation_organisation'), ['organisation'], unique=False)

    with op.batch_alter_table('local_plan_timetable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_plan_timetable_end_date'), ['end_date'], unique=False)

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organisation_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_organisation_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organisation_name'))
        batch_op.drop_index(batch_op.f('ix_organisation_end_date'))

    with op.batch_alter_table('local_plan_timetable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_plan_timetable_end_date'))

    with op.batch_alter_table('local_plan_organisation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_plan_organisation_organisation'))
        batch_op.drop_index(batch_op.f('ix_local_plan_organisation_local_plan'))

    with op.batch_alter_table('local_plan_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_plan_document_end_date'))

    with op.batch_alter_table('local_plan_boundary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_plan_boundary_end_date'))

    with op.batch_alter_table('local_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_plan_end_date'))

    # ### end Alembic commands ###
