"""remove event category

Revision ID: 72095fc4eab8
Revises: b58824f7c7b9
Create Date: 2024-12-06 17:59:55.673231

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "72095fc4eab8"
down_revision = "b58824f7c7b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("local_plan_event_type", schema=None) as batch_op:
        batch_op.drop_column("event_category")

    with op.batch_alter_table("local_plan_timetable", schema=None) as batch_op:
        batch_op.drop_column("event_category")

    sa.Enum(
        "TIMETABLE_PUBLISHED",
        "ESTIMATED_REGULATION_18",
        "ESTIMATED_REGULATION_19",
        "ESTIMATED_EXAMINATION_AND_ADOPTION",
        "REGULATION_18",
        "REGULATION_19",
        "PLANNING_INSPECTORATE_EXAMINATION",
        "PLANNING_INSPECTORATE_FINDINGS",
        name="eventcategory",
    ).drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "TIMETABLE_PUBLISHED",
        "ESTIMATED_REGULATION_18",
        "ESTIMATED_REGULATION_19",
        "ESTIMATED_EXAMINATION_AND_ADOPTION",
        "REGULATION_18",
        "REGULATION_19",
        "PLANNING_INSPECTORATE_EXAMINATION",
        "PLANNING_INSPECTORATE_FINDINGS",
        name="eventcategory",
    ).create(op.get_bind())
    with op.batch_alter_table("local_plan_timetable", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "event_category",
                postgresql.ENUM(
                    "TIMETABLE_PUBLISHED",
                    "ESTIMATED_REGULATION_18",
                    "ESTIMATED_REGULATION_19",
                    "ESTIMATED_EXAMINATION_AND_ADOPTION",
                    "REGULATION_18",
                    "REGULATION_19",
                    "PLANNING_INSPECTORATE_EXAMINATION",
                    "PLANNING_INSPECTORATE_FINDINGS",
                    name="eventcategory",
                    create_type=False,
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("local_plan_event_type", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "event_category",
                postgresql.ENUM(
                    "TIMETABLE_PUBLISHED",
                    "ESTIMATED_REGULATION_18",
                    "ESTIMATED_REGULATION_19",
                    "ESTIMATED_EXAMINATION_AND_ADOPTION",
                    "REGULATION_18",
                    "REGULATION_19",
                    "PLANNING_INSPECTORATE_EXAMINATION",
                    "PLANNING_INSPECTORATE_FINDINGS",
                    name="eventcategory",
                    create_type=False,
                ),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
