"""create timetable tables

Revision ID: 8896589fffa8
Revises: e10a80173836
Create Date: 2024-10-21 14:38:08.615005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8896589fffa8'
down_revision = 'e10a80173836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_event_type',
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('reference')
    )
    op.create_table('local_plan_timetable',
    sa.Column('reference', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('local_plan', sa.Text(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['local_plan'], ['local_plan.reference'], ),
    sa.PrimaryKeyConstraint('reference')
    )
    op.create_table('timetable_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('local_plan_timetable', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_type'], ['timetable_event_type.reference'], ),
    sa.ForeignKeyConstraint(['local_plan_timetable'], ['local_plan_timetable.reference'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_event')
    op.drop_table('local_plan_timetable')
    op.drop_table('timetable_event_type')
    # ### end Alembic commands ###
