"""add missing statistical geography column to org

Revision ID: bd14ce5152df
Revises: f2ebeaeb8b50
Create Date: 2024-09-27 12:36:58.029493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd14ce5152df'
down_revision = 'f2ebeaeb8b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statistical_geography', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.drop_column('statistical_geography')

    # ### end Alembic commands ###
