"""update event categories. split up examination and adoption

Revision ID: cb9300a49c91
Revises: 489466e2dc42
Create Date: 2024-11-11 14:32:46.673117

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'cb9300a49c91'
down_revision = '489466e2dc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'eventcategory', ['ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'PLANNING_INSPECTORATE_EXAMINATION', 'PLANNING_INSPECTORATE_FINDINGS'],
                        [TableReference(table_schema='public', table_name='local_plan_event', column_name='event_category')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'eventcategory', ['ESTIMATED_REGULATION_18', 'ESTIMATED_REGULATION_19', 'ESTIMATED_EXAMINATION_AND_ADOPTION', 'REGULATION_18', 'REGULATION_19', 'EXAMINATION_AND_ADOPTION'],
                        [TableReference(table_schema='public', table_name='local_plan_event', column_name='event_category')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
