"""Change status enum

Revision ID: e10a80173836
Revises: 079dc058c2fa
Create Date: 2024-10-17 14:28:24.819612

"""

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = "e10a80173836"
down_revision = "079dc058c2fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "status",
        ["FOR_REVIEW", "FOR_PLATFORM", "NOT_FOR_PLATFORM", "EXPORTED"],
        [
            TableReference(
                table_schema="public",
                table_name="local_plan",
                column_name="boundary_status",
            ),
            TableReference(
                table_schema="public", table_name="local_plan", column_name="status"
            ),
            TableReference(
                table_schema="public",
                table_name="local_plan_document",
                column_name="status",
            ),
        ],
        enum_values_to_rename=[
            ("FOR_PUBLICATION", "FOR_PLATFORM"),
            ("NOT_FOR_PUBLICATION", "NOT_FOR_PLATFORM"),
            ("PUBLISHED", "EXPORTED"),
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "status",
        ["FOR_REVIEW", "FOR_PUBLICATION", "NOT_FOR_PUBLICATION", "PUBLISHED"],
        [
            TableReference(
                table_schema="public",
                table_name="local_plan",
                column_name="boundary_status",
            ),
            TableReference(
                table_schema="public", table_name="local_plan", column_name="status"
            ),
            TableReference(
                table_schema="public",
                table_name="local_plan_document",
                column_name="status",
            ),
        ],
        enum_values_to_rename=[
            ("FOR_PLATFORM", "FOR_PUBLICATION"),
            ("NOT_FOR_PLATFORM", "NOT_FOR_PUBLICATION"),
            ("EXPORTED", "PUBLISHED"),
        ],
    )

    # ### end Alembic commands ###
