"""add day, month, and year to event

Revision ID: ff224e3917b3
Revises: 6df247d4e44c
Create Date: 2024-10-28 10:02:27.903042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff224e3917b3'
down_revision = '6df247d4e44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_day', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_month', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('event_year', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_plan_event', schema=None) as batch_op:
        batch_op.drop_column('event_year')
        batch_op.drop_column('event_month')
        batch_op.drop_column('event_day')

    # ### end Alembic commands ###
